import type { ProductModel } from '@/types/product.model';

export const products: ProductModel[] = [
  {
    _id: "1",
    name: "Apple iPhone 14 Pro",
    description:
      "آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی Super Retina XDR است. دارای A16 Bionic و سیستم ProMotion",
    price: 100000,
    image: "https://picsum.photos/200/300",
    quantity: 10,
    category: "Apple",
    rating: 4.5,
    numReviews: 20,
    countInStock: 5,
    reviews: [],
    createdAt: new Date("2024-08-22"),
    updatedAt: new Date("2024-08-22"),
    __v: 0,
  },
  {
    _id: "2",
    name: "Apple iPhone 14 Pro",
    description:
      "آیفون 14 پرو دارای صفحه نمایش 6.1 اینچی Super Retina XDR است. دارای A16 Bionic و سیستم ProMotion",
    price: 100000,
    image: "https://picsum.photos/200/300",
    quantity: 15,
    category: "Apple",
    rating: 4.2,
    numReviews: 12,
    countInStock: 7,
    reviews: [],
    createdAt: new Date("2024-08-22"),
    updatedAt: new Date("2024-08-22"),
    __v: 0,
  },
  {
    _id: "3",
    name: "Samsung S25 Ultra",
    description:
      "گوشی سامسونگ با صفحه‌نمایش بزرگ، دوربین قوی و باتری بادوام برای تجربه‌ای حرفه‌ای از موبایل",
    price: 200000,
    image: "https://picsum.photos/200/300",
    quantity: 8,
    category: "Samsung",
    rating: 4.7,
    numReviews: 25,
    countInStock: 6,
    reviews: [],
    createdAt: new Date("2024-08-22"),
    updatedAt: new Date("2024-08-22"),
    __v: 0,
  },
];
